version: '3.8'

# To override database settings, create .env file or export environment variables:
# DB_URL=jdbc:sqlserver://your-host:1433;databaseName=YourDB;encrypt=false;trustServerCertificate=true
# DB_USERNAME=your-username  
# DB_PASSWORD=your-password

services:
  # Online Library Application
  onllib-app:
    build: .
    container_name: onllib-app
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=${DB_URL:-jdbc:sqlserver://host.docker.internal:1433;databaseName=OnlineLibrary;encrypt=false;trustServerCertificate=true}
      - DB_USERNAME=${DB_USERNAME:-sa}
      - DB_PASSWORD=${DB_PASSWORD:-YourPassword123}
    ports:
      - "8080:8080"
    volumes:
      - onllib_storage:/app/storage
      - onllib_keys:/app/keys
      - onllib_logs:/app/logs
    networks:
      - onllib-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: onllib-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - onllib-network
    depends_on:
      - onllib-app
    restart: unless-stopped

volumes:
  onllib_storage:
    driver: local
  onllib_keys:
    driver: local
  onllib_logs:
    driver: local

networks:
  onllib-network:
    driver: bridge
