version: '3.8'

services:
  # Online Library App - Staging
  onllib-app-staging:
    build: .
    container_name: onllib-app-staging
    environment:
      - SPRING_PROFILES_ACTIVE=staging
      - DB_URL=${DB_URL:-jdbc:sqlserver://host.docker.internal:1433;databaseName=OnlineLibraryStaging;encrypt=false;trustServerCertificate=true}
      - DB_USERNAME=${DB_USERNAME:-sa}
      - DB_PASSWORD=${DB_PASSWORD:-YourPassword123}
      - JWT_SECRET=OnlineLibraryStagingSecretKey2024!
      - SERVER_PORT=8080
    ports:
      - "8081:8080"
    volumes:
      - onllib_staging_storage:/app/storage
      - onllib_staging_keys:/app/keys
      - onllib_staging_logs:/app/logs
    networks:
      - onllib-staging-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Nginx for Staging
  nginx-staging:
    image: nginx:alpine
    container_name: onllib-nginx-staging
    ports:
      - "8082:80"
    volumes:
      - ./nginx/staging.conf:/etc/nginx/nginx.conf
    networks:
      - onllib-staging-network
    depends_on:
      - onllib-app-staging
    restart: unless-stopped

volumes:
  onllib_staging_storage:
    driver: local
  onllib_staging_keys:
    driver: local
  onllib_staging_logs:
    driver: local

networks:
  onllib-staging-network:
    driver: bridge
